# Generated by Django 5.2.8 on 2025-11-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomes',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
